/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as NexusRouteImport } from './routes/nexus'
import { Route as HubRouteImport } from './routes/hub'
import { Route as CoreRouteImport } from './routes/core'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ArchitectureIndexRouteImport } from './routes/architecture.index'
import { Route as UseCasesPublicSectorRouteImport } from './routes/use-cases/public-sector'
import { Route as UseCasesManufacturingRouteImport } from './routes/use-cases/manufacturing'
import { Route as UseCasesInsuranceRouteImport } from './routes/use-cases/insurance'
import { Route as UseCasesHealthcareRouteImport } from './routes/use-cases/healthcare'
import { Route as UseCasesBankingRouteImport } from './routes/use-cases/banking'
import { Route as ThesisWhySovereignRouteImport } from './routes/thesis.why-sovereign'
import { Route as ResourcesHardwareRouteImport } from './routes/resources.hardware'
import { Route as ResourcesArchitecturePaperRouteImport } from './routes/resources.architecture-paper'
import { Route as ArchitecturePermissionsRouteImport } from './routes/architecture.permissions'
import { Route as ArchitectureMultiTenantRouteImport } from './routes/architecture.multi-tenant'
import { Route as ArchitectureDataSpacesRouteImport } from './routes/architecture.data-spaces'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusRoute = NexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ArchitectureIndexRoute = ArchitectureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchitectureRoute,
} as any)
const UseCasesPublicSectorRoute = UseCasesPublicSectorRouteImport.update({
  id: '/public-sector',
  path: '/public-sector',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesManufacturingRoute = UseCasesManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesInsuranceRoute = UseCasesInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesHealthcareRoute = UseCasesHealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesBankingRoute = UseCasesBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => UseCasesRoute,
} as any)
const ThesisWhySovereignRoute = ThesisWhySovereignRouteImport.update({
  id: '/thesis/why-sovereign',
  path: '/thesis/why-sovereign',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesHardwareRoute = ResourcesHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesArchitecturePaperRoute =
  ResourcesArchitecturePaperRouteImport.update({
    id: '/architecture-paper',
    path: '/architecture-paper',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ArchitecturePermissionsRoute = ArchitecturePermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => ArchitectureRoute,
} as any)
const ArchitectureMultiTenantRoute = ArchitectureMultiTenantRouteImport.update({
  id: '/multi-tenant',
  path: '/multi-tenant',
  getParentRoute: () => ArchitectureRoute,
} as any)
const ArchitectureDataSpacesRoute = ArchitectureDataSpacesRouteImport.update({
  id: '/data-spaces',
  path: '/data-spaces',
  getParentRoute: () => ArchitectureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/hub': typeof HubRoute
  '/nexus': typeof NexusRoute
  '/platform': typeof PlatformRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/use-cases': typeof UseCasesRouteWithChildren
  '/vault': typeof VaultRoute
  '/architecture/data-spaces': typeof ArchitectureDataSpacesRoute
  '/architecture/multi-tenant': typeof ArchitectureMultiTenantRoute
  '/architecture/permissions': typeof ArchitecturePermissionsRoute
  '/resources/architecture-paper': typeof ResourcesArchitecturePaperRoute
  '/resources/hardware': typeof ResourcesHardwareRoute
  '/thesis/why-sovereign': typeof ThesisWhySovereignRoute
  '/use-cases/banking': typeof UseCasesBankingRoute
  '/use-cases/healthcare': typeof UseCasesHealthcareRoute
  '/use-cases/insurance': typeof UseCasesInsuranceRoute
  '/use-cases/manufacturing': typeof UseCasesManufacturingRoute
  '/use-cases/public-sector': typeof UseCasesPublicSectorRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/hub': typeof HubRoute
  '/nexus': typeof NexusRoute
  '/platform': typeof PlatformRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/vault': typeof VaultRoute
  '/architecture/data-spaces': typeof ArchitectureDataSpacesRoute
  '/architecture/multi-tenant': typeof ArchitectureMultiTenantRoute
  '/architecture/permissions': typeof ArchitecturePermissionsRoute
  '/resources/architecture-paper': typeof ResourcesArchitecturePaperRoute
  '/resources/hardware': typeof ResourcesHardwareRoute
  '/thesis/why-sovereign': typeof ThesisWhySovereignRoute
  '/use-cases/banking': typeof UseCasesBankingRoute
  '/use-cases/healthcare': typeof UseCasesHealthcareRoute
  '/use-cases/insurance': typeof UseCasesInsuranceRoute
  '/use-cases/manufacturing': typeof UseCasesManufacturingRoute
  '/use-cases/public-sector': typeof UseCasesPublicSectorRoute
  '/architecture': typeof ArchitectureIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/contact': typeof ContactRoute
  '/core': typeof CoreRoute
  '/hub': typeof HubRoute
  '/nexus': typeof NexusRoute
  '/platform': typeof PlatformRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/use-cases': typeof UseCasesRouteWithChildren
  '/vault': typeof VaultRoute
  '/architecture/data-spaces': typeof ArchitectureDataSpacesRoute
  '/architecture/multi-tenant': typeof ArchitectureMultiTenantRoute
  '/architecture/permissions': typeof ArchitecturePermissionsRoute
  '/resources/architecture-paper': typeof ResourcesArchitecturePaperRoute
  '/resources/hardware': typeof ResourcesHardwareRoute
  '/thesis/why-sovereign': typeof ThesisWhySovereignRoute
  '/use-cases/banking': typeof UseCasesBankingRoute
  '/use-cases/healthcare': typeof UseCasesHealthcareRoute
  '/use-cases/insurance': typeof UseCasesInsuranceRoute
  '/use-cases/manufacturing': typeof UseCasesManufacturingRoute
  '/use-cases/public-sector': typeof UseCasesPublicSectorRoute
  '/architecture/': typeof ArchitectureIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/compliance'
    | '/contact'
    | '/core'
    | '/hub'
    | '/nexus'
    | '/platform'
    | '/resources'
    | '/use-cases'
    | '/vault'
    | '/architecture/data-spaces'
    | '/architecture/multi-tenant'
    | '/architecture/permissions'
    | '/resources/architecture-paper'
    | '/resources/hardware'
    | '/thesis/why-sovereign'
    | '/use-cases/banking'
    | '/use-cases/healthcare'
    | '/use-cases/insurance'
    | '/use-cases/manufacturing'
    | '/use-cases/public-sector'
    | '/architecture/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/contact'
    | '/core'
    | '/hub'
    | '/nexus'
    | '/platform'
    | '/use-cases'
    | '/vault'
    | '/architecture/data-spaces'
    | '/architecture/multi-tenant'
    | '/architecture/permissions'
    | '/resources/architecture-paper'
    | '/resources/hardware'
    | '/thesis/why-sovereign'
    | '/use-cases/banking'
    | '/use-cases/healthcare'
    | '/use-cases/insurance'
    | '/use-cases/manufacturing'
    | '/use-cases/public-sector'
    | '/architecture'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/compliance'
    | '/contact'
    | '/core'
    | '/hub'
    | '/nexus'
    | '/platform'
    | '/resources'
    | '/use-cases'
    | '/vault'
    | '/architecture/data-spaces'
    | '/architecture/multi-tenant'
    | '/architecture/permissions'
    | '/resources/architecture-paper'
    | '/resources/hardware'
    | '/thesis/why-sovereign'
    | '/use-cases/banking'
    | '/use-cases/healthcare'
    | '/use-cases/insurance'
    | '/use-cases/manufacturing'
    | '/use-cases/public-sector'
    | '/architecture/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  ContactRoute: typeof ContactRoute
  CoreRoute: typeof CoreRoute
  HubRoute: typeof HubRoute
  NexusRoute: typeof NexusRoute
  PlatformRoute: typeof PlatformRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  UseCasesRoute: typeof UseCasesRouteWithChildren
  VaultRoute: typeof VaultRoute
  ThesisWhySovereignRoute: typeof ThesisWhySovereignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus': {
      id: '/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof NexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/architecture/': {
      id: '/architecture/'
      path: '/'
      fullPath: '/architecture/'
      preLoaderRoute: typeof ArchitectureIndexRouteImport
      parentRoute: typeof ArchitectureRoute
    }
    '/use-cases/public-sector': {
      id: '/use-cases/public-sector'
      path: '/public-sector'
      fullPath: '/use-cases/public-sector'
      preLoaderRoute: typeof UseCasesPublicSectorRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/manufacturing': {
      id: '/use-cases/manufacturing'
      path: '/manufacturing'
      fullPath: '/use-cases/manufacturing'
      preLoaderRoute: typeof UseCasesManufacturingRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/insurance': {
      id: '/use-cases/insurance'
      path: '/insurance'
      fullPath: '/use-cases/insurance'
      preLoaderRoute: typeof UseCasesInsuranceRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/healthcare': {
      id: '/use-cases/healthcare'
      path: '/healthcare'
      fullPath: '/use-cases/healthcare'
      preLoaderRoute: typeof UseCasesHealthcareRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/banking': {
      id: '/use-cases/banking'
      path: '/banking'
      fullPath: '/use-cases/banking'
      preLoaderRoute: typeof UseCasesBankingRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/thesis/why-sovereign': {
      id: '/thesis/why-sovereign'
      path: '/thesis/why-sovereign'
      fullPath: '/thesis/why-sovereign'
      preLoaderRoute: typeof ThesisWhySovereignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/hardware': {
      id: '/resources/hardware'
      path: '/hardware'
      fullPath: '/resources/hardware'
      preLoaderRoute: typeof ResourcesHardwareRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/architecture-paper': {
      id: '/resources/architecture-paper'
      path: '/architecture-paper'
      fullPath: '/resources/architecture-paper'
      preLoaderRoute: typeof ResourcesArchitecturePaperRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/architecture/permissions': {
      id: '/architecture/permissions'
      path: '/permissions'
      fullPath: '/architecture/permissions'
      preLoaderRoute: typeof ArchitecturePermissionsRouteImport
      parentRoute: typeof ArchitectureRoute
    }
    '/architecture/multi-tenant': {
      id: '/architecture/multi-tenant'
      path: '/multi-tenant'
      fullPath: '/architecture/multi-tenant'
      preLoaderRoute: typeof ArchitectureMultiTenantRouteImport
      parentRoute: typeof ArchitectureRoute
    }
    '/architecture/data-spaces': {
      id: '/architecture/data-spaces'
      path: '/data-spaces'
      fullPath: '/architecture/data-spaces'
      preLoaderRoute: typeof ArchitectureDataSpacesRouteImport
      parentRoute: typeof ArchitectureRoute
    }
  }
}

interface ArchitectureRouteChildren {
  ArchitectureDataSpacesRoute: typeof ArchitectureDataSpacesRoute
  ArchitectureMultiTenantRoute: typeof ArchitectureMultiTenantRoute
  ArchitecturePermissionsRoute: typeof ArchitecturePermissionsRoute
  ArchitectureIndexRoute: typeof ArchitectureIndexRoute
}

const ArchitectureRouteChildren: ArchitectureRouteChildren = {
  ArchitectureDataSpacesRoute: ArchitectureDataSpacesRoute,
  ArchitectureMultiTenantRoute: ArchitectureMultiTenantRoute,
  ArchitecturePermissionsRoute: ArchitecturePermissionsRoute,
  ArchitectureIndexRoute: ArchitectureIndexRoute,
}

const ArchitectureRouteWithChildren = ArchitectureRoute._addFileChildren(
  ArchitectureRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesArchitecturePaperRoute: typeof ResourcesArchitecturePaperRoute
  ResourcesHardwareRoute: typeof ResourcesHardwareRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesArchitecturePaperRoute: ResourcesArchitecturePaperRoute,
  ResourcesHardwareRoute: ResourcesHardwareRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface UseCasesRouteChildren {
  UseCasesBankingRoute: typeof UseCasesBankingRoute
  UseCasesHealthcareRoute: typeof UseCasesHealthcareRoute
  UseCasesInsuranceRoute: typeof UseCasesInsuranceRoute
  UseCasesManufacturingRoute: typeof UseCasesManufacturingRoute
  UseCasesPublicSectorRoute: typeof UseCasesPublicSectorRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesBankingRoute: UseCasesBankingRoute,
  UseCasesHealthcareRoute: UseCasesHealthcareRoute,
  UseCasesInsuranceRoute: UseCasesInsuranceRoute,
  UseCasesManufacturingRoute: UseCasesManufacturingRoute,
  UseCasesPublicSectorRoute: UseCasesPublicSectorRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  ContactRoute: ContactRoute,
  CoreRoute: CoreRoute,
  HubRoute: HubRoute,
  NexusRoute: NexusRoute,
  PlatformRoute: PlatformRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  UseCasesRoute: UseCasesRouteWithChildren,
  VaultRoute: VaultRoute,
  ThesisWhySovereignRoute: ThesisWhySovereignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
